id: P008066
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18862
  title: མེ་གསོད་མེ་འགོག་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    7e30d61a0462426cbd496f8e15a1dbea:
      image_group_id: I8LS18864
      title: Volume 1 of me gsod me 'gog skor gyi krung hwa mi dmangs spyi mthun rgyal
        khab kyi bca' khrims/
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
