id: P008066
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18862
  title: མེ་གསོད་མེ་འགོག་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    a132dd01d2cc4015bd480fe2051a2692:
      image_group_id: I8LS18864
      title: ''
      volume_number: 1
      total_pages: 66
ebook_metadata:
  title: མེ་གསོད་མེ་འགོག་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  sku: P008066
  cover: cover.jpg
  layers:
  - pagination
