id: I33121FB2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:49:08+00:00'
last_modified: '2022-06-08T18:11:17.380262+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18862
  title: མེ་གསོད་མེ་འགོག་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    20B0:
      image_group_id: I8LS18864
      title: Volume 1 of me gsod me 'gog skor gyi krung hwa mi dmangs spyi mthun rgyal
        khab kyi bca' khrims/
      total_pages: 66
      order: 1
      base_file: 20B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
